### PR TITLE
Build libraries to only depend dynamically in libc++. In Linux link a…

### PR DESCRIPTION
**Pull request by leohahn**
…gainst libc++ as well instead of libstdc++ (in order to fix a bug in unity 2018 beta)

### CODE REVIEW

**Comment by felipejfc** [comment]
awesome! are the building instructions in the readme updated? if no, can you update them?

**Comment by leohahn** [comment]
yup, forgot about the readme

**Comment by felipejfc** [comment]
@leohahn is this ready to be merged?

**Comment by leohahn** [comment]
Yes, I updated the readme and the docker image.

**Pull request merged**
